# Generated by Django 4.0.6 on 2022-11-20 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_strategy', models.CharField(choices=[('LIFO', 'LIFO'), ('FIFO', 'FIFO')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedRequestManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('donation_hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status_donation', models.CharField(blank=True, choices=[('available', 'available'), ('booked', 'booked')], default='available', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('donation_hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status_help_request', models.CharField(blank=True, choices=[('satisfied', 'satisfied'), ('unsatisfied', 'unsatisfied')], default='unsatisfied', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='склад')),
                ('capacity', models.IntegerField(verbose_name='вместимость')),
                ('ocupied', models.IntegerField(verbose_name='заполненость')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
            },
        ),
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charity.baseitem')),
                ('state', models.CharField(max_length=250)),
                ('amount', models.IntegerField(default=1)),
            ],
            bases=('charity.baseitem',),
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charity.baseitem')),
                ('amount_it', models.IntegerField(default=1)),
            ],
            bases=('charity.baseitem',),
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя вещи')),
                ('type_thing', models.CharField(max_length=255, verbose_name='тип вещи')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charity.category')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
            },
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.CheckConstraint(check=models.Q(('ocupied__lte', django.db.models.expressions.F('capacity'))), name='ocupied_lte_capasity'),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='base_item_hash',
            field=models.ForeignKey(db_column='base_item_hash', on_delete=django.db.models.deletion.CASCADE, to='charity.thing'),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.office', verbose_name='склад'),
        ),
        migrations.CreateModel(
            name='CompletedRequest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('charity.helprequest',),
        ),
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('donationitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charity.donationitem')),
                ('details', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('condition', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='images/%Y/%m/%d/')),
            ],
            bases=('charity.donationitem',),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.helprequest'),
        ),
        migrations.AddField(
            model_name='donationitem',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.donation'),
        ),
    ]
