# Generated by Django 4.0.6 on 2022-11-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitem',
            name='amount_it',
        ),
    ]
