# Generated by Django 4.0.6 on 2022-11-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_remove_requestitem_amount_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='amount_req_item',
            field=models.IntegerField(default=1),
        ),
    ]
