# Generated by Django 4.0.6 on 2022-08-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_good_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='stock',
            field=models.CharField(default='LIFO', max_length=50),
            preserve_default=False,
        ),
    ]
