# Generated by Django 4.0.6 on 2022-11-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_requestitem_amount_req_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='status_help_request',
            field=models.CharField(blank=True, choices=[('satisfied', 'satisfied'), ('unsatisfied', 'unsatisfied'), ('waiting', 'waiting')], default='unsatisfied', max_length=250),
        ),
    ]
