# Generated by Django 4.0.6 on 2022-08-08 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_good_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('capacity', models.IntegerField()),
                ('ocupied', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='good',
            old_name='name_good',
            new_name='thing',
        ),
        migrations.AddField(
            model_name='good',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='office',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='charity.office'),
            preserve_default=False,
        ),
    ]
