# Generated by Django 4.0.6 on 2022-08-12 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_office_rename_name_good_good_thing_good_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['-stock', '-time_create'], 'verbose_name': 'Вещь', 'verbose_name_plural': 'Вещи которые принесли'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['ocupied'], 'verbose_name': 'склад', 'verbose_name_plural': 'склады'},
        ),
        migrations.AlterField(
            model_name='good',
            name='amount',
            field=models.IntegerField(verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='good',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.office', verbose_name='склад'),
        ),
        migrations.AlterField(
            model_name='good',
            name='state',
            field=models.CharField(max_length=100, verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='good',
            name='stock',
            field=models.CharField(max_length=50, verbose_name='тип сортировки'),
        ),
        migrations.AlterField(
            model_name='good',
            name='thing',
            field=models.CharField(max_length=50, verbose_name='вещь'),
        ),
        migrations.AlterField(
            model_name='good',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(max_length=250, verbose_name='склад'),
        ),
        migrations.AlterField(
            model_name='office',
            name='capacity',
            field=models.IntegerField(verbose_name='вместимость'),
        ),
        migrations.AlterField(
            model_name='office',
            name='ocupied',
            field=models.IntegerField(verbose_name='заполненость'),
        ),
    ]
