# Generated by Django 4.0.6 on 2022-11-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_alter_helprequest_status_help_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status_donation',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('booked', 'booked'), ('used', 'used')], default='available', max_length=250),
        ),
    ]
