# Generated by Django 4.0.6 on 2022-10-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_alter_good_options_alter_office_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='state',
            field=models.CharField(choices=[('rq', 'requested'), ('avlb', 'available'), ('bkd', 'booked'), ('shp', 'shipped')], max_length=100, verbose_name='состояние'),
        ),
    ]
